name: ATM651
channels:
  - conda-forge
  - pyviz
  - defaults
dependencies:
   - python=3
   - numpy
   - matplotlib
   - cartopy
   - jupyter
   - netcdf4
   - owslib
   - metpy
   - pint
   - shapely
   - siphon
   - xarray
   - fastparquet
   - psutil
   - fsspec
   - pip
   - ffmpeg
   - pytest
   - pip:
     - mpldatacursor
     - ipyidv
     - mseplots-pkg
